name: xpcl
description: >
  An experimental command-line interface for menu-based games.

version: 0.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  meta: ^1.7.0
